"""empty message

Revision ID: 06259d645dd6
Revises: 7b56705cb3b1
Create Date: 2019-10-18 22:32:18.099162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06259d645dd6'
down_revision = '7b56705cb3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('wool', sa.Integer(), nullable=True),
    sa.Column('elastane', sa.Integer(), nullable=True),
    sa.Column('polyester', sa.Integer(), nullable=True),
    sa.Column('viscose', sa.Integer(), nullable=True),
    sa.Column('flax', sa.Integer(), nullable=True),
    sa.Column('cashmere', sa.Integer(), nullable=True),
    sa.Column('cost', sa.DECIMAL(precision=9, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('data', sa.String(length=250), nullable=True),
    sa.Column('slug', sa.String(length=140), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=9, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('suit_fabrics',
    sa.Column('suit_id', sa.Integer(), nullable=True),
    sa.Column('fabric_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabric.id'], ),
    sa.ForeignKeyConstraint(['suit_id'], ['suit.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suit_fabrics')
    op.drop_table('suit')
    op.drop_table('fabric')
    # ### end Alembic commands ###
