"""empty message

Revision ID: 10f86005b1a5
Revises: 
Create Date: 2019-10-27 16:58:40.198652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f86005b1a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('surname', sa.String(length=140), nullable=True),
    sa.Column('patronymic', sa.String(length=140), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=140), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fabric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('wool', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=140), nullable=True),
    sa.Column('elastane', sa.Integer(), nullable=True),
    sa.Column('polyester', sa.Integer(), nullable=True),
    sa.Column('viscose', sa.Integer(), nullable=True),
    sa.Column('flax', sa.Integer(), nullable=True),
    sa.Column('cashmere', sa.Integer(), nullable=True),
    sa.Column('cost', sa.DECIMAL(precision=9, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('suit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('data', sa.String(length=250), nullable=True),
    sa.Column('slug', sa.String(length=140), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=9, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tailor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('surname', sa.String(length=140), nullable=True),
    sa.Column('patronymic', sa.String(length=140), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=140), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suit_consultants',
    sa.Column('suit_id', sa.Integer(), nullable=True),
    sa.Column('consultant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consultant_id'], ['consultant.id'], ),
    sa.ForeignKeyConstraint(['suit_id'], ['suit.id'], )
    )
    op.create_table('suit_fabrics',
    sa.Column('suit_id', sa.Integer(), nullable=True),
    sa.Column('fabric_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabric.id'], ),
    sa.ForeignKeyConstraint(['suit_id'], ['suit.id'], )
    )
    op.create_table('suit_tailors',
    sa.Column('suit_id', sa.Integer(), nullable=True),
    sa.Column('tailor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['suit_id'], ['suit.id'], ),
    sa.ForeignKeyConstraint(['tailor_id'], ['tailor.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suit_tailors')
    op.drop_table('suit_fabrics')
    op.drop_table('suit_consultants')
    op.drop_table('tailor')
    op.drop_table('suit')
    op.drop_table('fabric')
    op.drop_table('consultant')
    # ### end Alembic commands ###
