"""empty message

Revision ID: 22fddbc5cbd1
Revises: 85e50a26694d
Create Date: 2019-11-16 15:37:21.381256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fddbc5cbd1'
down_revision = '85e50a26694d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('price', sa.DECIMAL(precision=9, scale=2), nullable=True))
    op.add_column('suit', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suit', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suit', type_='foreignkey')
    op.drop_column('suit', 'order_id')
    op.drop_column('order', 'price')
    # ### end Alembic commands ###
