"""empty message

Revision ID: 3e5189bf9914
Revises: 22fddbc5cbd1
Create Date: 2019-11-16 15:48:32.462188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5189bf9914'
down_revision = '22fddbc5cbd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('suit', sa.Column('priority_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suit', 'priority', ['priority_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suit', type_='foreignkey')
    op.drop_column('suit', 'priority_id')
    op.drop_table('priority')
    # ### end Alembic commands ###
