"""empty message

Revision ID: 4c13498b0158
Revises: 883093bb7615
Create Date: 2019-11-16 15:21:26.323693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c13498b0158'
down_revision = '883093bb7615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('suit', sa.Column('kit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suit', 'kit', ['kit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suit', type_='foreignkey')
    op.drop_column('suit', 'kit_id')
    op.drop_table('kit')
    # ### end Alembic commands ###
