"""empty message

Revision ID: 64de7c70e313
Revises: 435fceea3e0c
Create Date: 2019-11-18 20:53:17.425361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64de7c70e313'
down_revision = '435fceea3e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_bracket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fabric', sa.Column('pattern_id', sa.Integer(), nullable=True))
    op.add_column('fabric', sa.Column('price_bracket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fabric', 'price_bracket', ['price_bracket_id'], ['id'])
    op.create_foreign_key(None, 'fabric', 'pattern', ['pattern_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fabric', type_='foreignkey')
    op.drop_constraint(None, 'fabric', type_='foreignkey')
    op.drop_column('fabric', 'price_bracket_id')
    op.drop_column('fabric', 'pattern_id')
    op.drop_table('price_bracket')
    op.drop_table('pattern')
    # ### end Alembic commands ###
