"""empty message

Revision ID: 69c220294cb8
Revises: 7e133db55bd8
Create Date: 2019-11-18 21:23:37.462507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c220294cb8'
down_revision = '7e133db55bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('consultant', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('consultant', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.add_column('consultant', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'consultant', 'shop', ['shop_id'], ['id'])
    op.create_foreign_key(None, 'consultant', 'status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'consultant', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consultant', type_='foreignkey')
    op.drop_constraint(None, 'consultant', type_='foreignkey')
    op.drop_constraint(None, 'consultant', type_='foreignkey')
    op.drop_column('consultant', 'status_id')
    op.drop_column('consultant', 'shop_id')
    op.drop_column('consultant', 'role_id')
    op.drop_table('shop')
    # ### end Alembic commands ###
