"""empty message

Revision ID: 7b56705cb3b1
Revises: 
Create Date: 2019-10-18 21:15:50.465152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b56705cb3b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('slug', table_name='suit')
    op.drop_table('suit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suit',
    sa.Column('suit_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=140), nullable=True),
    sa.Column('data', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=True),
    sa.Column('slug', mysql.VARCHAR(collation='utf8_unicode_ci', length=140), nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('suit_id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('slug', 'suit', ['slug'], unique=True)
    # ### end Alembic commands ###
