"""empty message

Revision ID: 7dbd4f02f0f7
Revises: 10f86005b1a5
Create Date: 2019-11-02 12:18:18.625279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dbd4f02f0f7'
down_revision = '10f86005b1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suit', 'title',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=140),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suit', 'title',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=140),
               nullable=True)
    # ### end Alembic commands ###
