"""empty message

Revision ID: 883093bb7615
Revises: f2f0fbb2cf5b
Create Date: 2019-11-16 15:16:47.307080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883093bb7615'
down_revision = 'f2f0fbb2cf5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('suit', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suit', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suit', type_='foreignkey')
    op.drop_column('suit', 'status_id')
    op.drop_table('status')
    # ### end Alembic commands ###
