"""empty message

Revision ID: 9c985af0eef9
Revises: ff8cc872ee24
Create Date: 2019-11-18 22:01:24.042768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c985af0eef9'
down_revision = 'ff8cc872ee24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('suit_ibfk_3', 'suit', type_='foreignkey')
    op.drop_column('suit', 'consultant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suit', sa.Column('consultant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('suit_ibfk_3', 'suit', 'consultant', ['consultant_id'], ['id'])
    # ### end Alembic commands ###
