"""empty message

Revision ID: a317b8df104c
Revises: ed469a38dbea
Create Date: 2019-11-16 14:33:17.832678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a317b8df104c'
down_revision = 'ed469a38dbea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suit_consultants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suit_consultants',
    sa.Column('suit_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('consultant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['consultant_id'], ['consultant.id'], name='suit_consultants_ibfk_2'),
    sa.ForeignKeyConstraint(['suit_id'], ['suit.id'], name='suit_consultants_ibfk_1'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
