"""empty message

Revision ID: a6cd024e6680
Revises: 3e5189bf9914
Create Date: 2019-11-18 20:28:08.455186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6cd024e6680'
down_revision = '3e5189bf9914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kit', sa.Column('suit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'kit', 'suit', ['suit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kit', type_='foreignkey')
    op.drop_column('kit', 'suit_id')
    # ### end Alembic commands ###
