"""empty message

Revision ID: c23bda6d48aa
Revises: 
Create Date: 2019-11-16 14:23:44.231789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c23bda6d48aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suit_tailors')
    op.add_column('suit', sa.Column('tailor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suit', 'tailor', ['tailor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suit', type_='foreignkey')
    op.drop_column('suit', 'tailor_id')
    op.create_table('suit_tailors',
    sa.Column('suit_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tailor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['suit_id'], ['suit.id'], name='suit_tailors_ibfk_1'),
    sa.ForeignKeyConstraint(['tailor_id'], ['tailor.id'], name='suit_tailors_ibfk_2'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
