"""empty message

Revision ID: d26674e7317e
Revises: a317b8df104c
Create Date: 2019-11-16 14:41:28.576774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26674e7317e'
down_revision = 'a317b8df104c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('suit', sa.Column('garment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suit', 'garment', ['garment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suit', type_='foreignkey')
    op.drop_column('suit', 'garment_id')
    op.drop_table('garment')
    # ### end Alembic commands ###
