"""empty message

Revision ID: eb9bb7f3d793
Revises: 95135a8da541
Create Date: 2019-11-18 21:42:25.219740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9bb7f3d793'
down_revision = '95135a8da541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('surname', sa.String(length=140), nullable=True),
    sa.Column('patronymic', sa.String(length=140), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=140), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('scan', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scan', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scan', type_='foreignkey')
    op.drop_column('scan', 'customer_id')
    op.drop_table('customer')
    # ### end Alembic commands ###
