"""empty message

Revision ID: ed469a38dbea
Revises: c23bda6d48aa
Create Date: 2019-11-16 14:31:44.190039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed469a38dbea'
down_revision = 'c23bda6d48aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suit', sa.Column('consultant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suit', 'consultant', ['consultant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suit', type_='foreignkey')
    op.drop_column('suit', 'consultant_id')
    # ### end Alembic commands ###
