"""empty message

Revision ID: ff8cc872ee24
Revises: eb9bb7f3d793
Create Date: 2019-11-18 21:54:04.023631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8cc872ee24'
down_revision = 'eb9bb7f3d793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('delivery_type_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'delivery_type', ['delivery_type_id'], ['id'])
    op.create_foreign_key(None, 'order', 'shop', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'shop_id')
    op.drop_column('order', 'delivery_type_id')
    op.drop_table('delivery_type')
    # ### end Alembic commands ###
